### ISSUE TITLE
Draw & End Turn not working for Scout

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#250]
Module V5.1.0beta5
Vassal V3.7.14
Scenario 001 Rolica (French First Position) - 17 August 1808

Playing Solitaire, the "Draw & End Turn" button in Allies Hand does not properly handle a Scout end turn card draw. One card at a time is automatically drawn and automatically discarded not letting the player choose one. The game does not pass the turn over to the French player. Connected to issue 245 since Scout end turn using the "Draw & End Turn" button worked on previous betas (beta1)?

[ScoutEndTurnBug.zip](https://github.com/user-attachments/files/16747303/ScoutEndTurnBug.zip)

**Comment by riverwanderer** [comment]
ouch. Thanks.

**Comment by utl94** [comment]
No worries. Something seems to have broken with the end turn mechanism when auto discard is in effect for Solitaire. I haven't checked every card but e.g. Élan end turn seems to be working. Note: Scout seem to work as intended when played as Allies/French and switching sides rather than playing Solitaire.

**Comment by riverwanderer** [comment]
Your diagnosis was spot on, thank you. The Solitaire change should have been be inhibited when the card is ObscuredToOthers. It is specifically Scout cards affected I think, because Scout uses the same "Play" mechanism to move drawn cards to the main board.  Fix will be in beta6 which I will push to Vassal today. You can try the dev version now if you wish - [here](https://www.dropbox.com/scl/fi/zhbr3mchsxdzv0bvrnlkm/CCNapoleonics5_1_0_DEV.vmod?rlkey=lk25n7sn2gzaasz93frfpkj78&dl=0).

**Comment by utl94** [comment]
Geez, you are working fast! I take the opportunity to thank you for your dedication and for providing a wonderful module.

**Comment by riverwanderer** [comment]
Fix in a504.
