### ISSUE TITLE
Enhanced behaviour for Counter Attack Command card

### ISSUE THREAD

**Issue by utl94** [riverwanderer/ccnapoleonics#260]
Module V5.1.0beta6
Vassal V3.7.14
Scenario 001 Rolica (French First Position) - 17 August 1808

The Counter Attack Command card appears to display different functions depending on location.
  * In hand: card displays which card is being countered with the effect the the "wrong" section is being shown w.r.t actual play effect in cases of Left and Right sections.
  * On game board: card switches to display the correct section in which the card will take effect.
  * In discard pile: card is cleared and no longer displays what action the card countered. This is problematic if #259 is resolved to auto discard Counter Attack.

Plea for making Counter Attack always display the card function it will/is/has counter/ing/ed as well as switching to the (Left/Right) section where the card is played.

**Comment by riverwanderer** [comment]
To check my understanding, if Player A plays "Attack Left", you would like Player B's Counter-Attack to display "Attack Left" and never to display "Attack Right" ?

Another situation to consider is when Player A also holds Counter-Attack; here, if Player B does play Counter-Attack then Player A's Counter-Attack must interpret the played card as an "Attack Left". This is the technical reason why Player B's Counter-Attack card changes the _activeCard_ property to "Attack Right", which is in turn what the card displays.

Discard is not so problematic, since the Counter-Attack action is reported to the chat log, and we are talking about Solitaire here - who should know which card they have Countered. Sections can get confusing even for Solitaire but the order-monitor will flag up any error there.

To keep a consistent display on the card, including on the discard pile, the display value could be set on the card when it is play. This might be a way to meet this request. 

I would like to address #259 first and see if anyone else has feedback on the current display behaviour.

**Comment by utl94** [comment]
What I reacted to was the three different ways of how Counter Attack is displayed to me as a player (one way in the hand, another on the board after play, and a third way in the discard pile).

What I certainly wish is that if Player A plays "Attack Left", I would like Player B's Counter-Attack to display "Attack Right" when the Counter Attack Command card is on the board (current behaviour). I further would like the card to continue to display this while in the discard play in the current turn IF it will be auto-discarded in Solitaire mode.

I am honestly not certain what I prefer for the card to display while in the hand (either what card is countered (current behaviour) or what will Counter Attack "be" played as)?

**Comment by riverwanderer** [comment]
To rationalise the behaviour, I have settled on Counter-Attack showing the name of the card that it will Counter.

It follows that at some point in the turn, when countering a flank card, Counter-Attack will switch the flank that it displays. In the current development version, this occurs when the Counter-Attack moves to the Discard pile. However, I will consider whether I can delay this switch until the end of the turn.

Associated with this change (at least in the development version (a8xx), there is a bug whereby the played Counter-Attack card always plays to the centre section, whereas it should play to the affected section as with other cards.

**Comment by riverwanderer** [comment]
Example of Counter-attack card indicating screen section for the card play:
<img width="188" alt="image" src="https://github.com/user-attachments/assets/59fee334-4705-42c6-94bb-33d5d26436a1">  in a827.
